apiVersion: v1
kind: Service
metadata:
  name: ambient-weather-mcp
  namespace: ambient-weather-mcp
spec:
  type: ClusterIP
  selector:
    app: ambient-weather-mcp
  ports:
    - port: 8080
      targetPort: 8080
